### ISSUE TITLE
Issues setting up the project

### ISSUE THREAD

**Issue by fnnhnsn** [nounsDAO/nouns-monorepo#868]
Hey everyone,
I'm probably missing a basic thing, so I'd definitely appreciate your help.

I cloned the project and tried to set it up locally, however the dependency installation is currently failing.

I am using a Macbook with a M1 chip and tried using node versions 20.11.1, 18.20.3 and 16.18.0.  As well, I tried Python versions 3.13 and 2.7.18.

I am executing `yarn install` in the root directory. Whenever I do that, I get this error and the installation finishes incomplete:

```
warning Error running install script for optional dependency: "/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-hid
Output:
prebuild-install WARN install No prebuilt binaries found (target=16.20.2 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@16.20.2 | darwin | arm64
gyp info find Python using Python version 2.7.18 found at \"/Users/finnhansen/.pyenv/versions/2.7.18/bin/python\"
(node:5926) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Users/finnhansen/.pyenv/versions/2.7.18/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/finnhansen/Library/Caches/node-gyp/16.20.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/finnhansen/Library/Caches/node-gyp/16.20.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/finnhansen/Library/Caches/node-gyp/16.20.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:612:31: error: too few arguments to function call, expected 3, have 2
  node::AtExit(deinitialize, 0);
  ~~~~~~~~~~~~                ^
/Users/finnhansen/Library/Caches/node-gyp/16.20.2/include/node/node.h:979:18: note: 'AtExit' declared here
NODE_EXTERN void AtExit(Environment* env,
                 ^
1 error generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 23.5.0
gyp ERR! command \"/Users/finnhansen/.nvm/versions/node/v16.20.2/bin/node\" \"/Users/finnhansen/Documents/dev/dao-monorepo/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/finnhansen/Documents/dev/dao-monorepo/node_modules/node-hid
$ lerna run prepare --scope=@nouns/{assets,contracts,sdk}
lerna notice cli v3.22.1
lerna notice filter including ["@nouns/assets","@nouns/contracts","@nouns/sdk"]
lerna info filter [ '@nouns/assets', '@nouns/contracts', '@nouns/sdk' ]
lerna info Executing command in 3 packages: "npm run prepare"
lerna ERR! npm run prepare exited 1 in '@nouns/contracts'
lerna ERR! npm run prepare stdout:

> @nouns/contracts@0.3.0 prepare
> yarn build

yarn run v1.22.22
$ yarn build:sol --force && yarn build:ts && yarn build:declarations
$ npx hardhat compile --force

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! npm run prepare stderr:
Solidity 0.8.23 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

An unexpected error occurred:
SyntaxError: /Users/finnhansen/Documents/dev/dao-monorepo/packages/nouns-contracts/cache/solidity-files-cache.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/finnhansen/Documents/dev/dao-monorepo/node_modules/jsonfile/index.js:33:18
    at /Users/finnhansen/Documents/dev/dao-monorepo/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
error Command failed with exit code 1.
error Command failed with exit code 1.
npm ERR! Lifecycle script `prepare` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @nouns/contracts@0.3.0
npm ERR!   at location: /Users/finnhansen/Documents/dev/dao-monorepo/packages/nouns-contracts

lerna ERR! npm run prepare exited 1 in '@nouns/contracts'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Might anyone have an idea what the issue could be? Thanks a lot in advance!

**Comment by volkyeth** [comment]
fixed by #894
